/*
 * Copyright 2026 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.sbt.journey.templates

import uk.gov.hmrc.sbt.journey.models.{FieldType, QualifiedName}
import uk.gov.hmrc.sbt.journey.templates.Imports.PlayJsonPrefix
import uk.gov.hmrc.sbt.journey.utils.StringCaseUtils.camelCase

object JourneyModel {
  private def switchCase(caseName: String, fields: List[(String, FieldType)]) = {
    if (fields.isEmpty)
      s"  case $caseName"
    else
      s"""|  case $caseName(
          |  ${fields
           .map((ModelFields.field _).tupled)
           .mkString("," + System.lineSeparator() + (" " * 2))}
          |  )""".stripMargin
  }

  private def switchCaseReads(caseName: String, fields: List[(String, FieldType)]): String = {
    if (fields.isEmpty) ""
    else s"  given ${camelCase(caseName)}Reads: Reads[$caseName] = Json.reads[$caseName]"
  }

  private def switchCaseWrites(caseName: String, fields: List[(String, FieldType)]): String = {
    if (fields.isEmpty) ""
    else s"  given ${camelCase(caseName)}Writes: Writes[$caseName] = Json.writes[$caseName]"
  }

  private def switchCaseRead(
    modelsPackage: QualifiedName,
    modelName: String,
    cse: (String, List[(String, FieldType)])
  ): String = {
    val (caseName, fields) = cse
    val nm                 = camelCase(caseName)
    val model              = modelsPackage / modelName
    val qualCaseName       = model / caseName
    if (fields.isEmpty)
      s"""|        case $nm if $nm == config.typeNaming("$qualCaseName")
          |          JsSuccess($caseName)""".stripMargin
    else
      s"""|        case $nm if $nm == config.typeNaming("$qualCaseName") =>
          |          ${nm}Reads.reads(obj.value.getOrElse("_value", obj))""".stripMargin
  }

  private def switchCaseWrite(
    modelsPackage: QualifiedName,
    modelName: String,
    cse: (String, List[(String, FieldType)])
  ): String = {
    val (caseName, fields) = cse
    val nm                 = camelCase(caseName)
    val model              = modelsPackage / modelName
    val qualCaseName       = model / caseName
    if (fields.isEmpty)
      s"""|    case $nm: $caseName =>
          |      Json.obj(config.discriminator -> config.typeNaming("$qualCaseName"))""".stripMargin
    else
      s"""|    case $nm: $caseName =>
          |      val output = ${nm}Writes.writes($nm) match {
          |        case obj: JsObject => obj
          |        case other: JsValue => Json.obj("_value" -> other)
          |      }
          |      output ++ Json.obj(config.discriminator -> config.typeNaming("$qualCaseName"))""".stripMargin
  }

  def forSwitchCase(
    modelsPackage: QualifiedName,
    modelName: String,
    modelCases: Map[String, List[(String, FieldType)]]
  ): String = {
    val playImports = Map(
      PlayJsonPrefix -> Set(
        "Json",
        "JsonConfiguration",
        "JsError",
        "JsObject",
        "JsPath",
        "JsValue",
        "Format",
        "Reads",
        "Writes"
      )
    )

    val importPrefixes = playImports ++ Imports.importedSymbols(modelCases.values.toList.flatten)
    val imports        = Imports.importsFor(modelsPackage, importPrefixes)
    val extendsClause  = FormatTraits.extendsClause(importPrefixes)

    val caseReads          = modelCases.map((switchCaseReads _).tupled)
    val caseWrites         = modelCases.map((switchCaseWrites _).tupled)
    val caseReadsAndWrites = (caseReads ++ caseWrites).toList.filterNot(_.isBlank)

    val subtypeReadsWrites =
      if (caseReadsAndWrites.isEmpty) ""
      else
        caseReadsAndWrites.mkString(
          System.lineSeparator(),
          System.lineSeparator(),
          System.lineSeparator()
        )

    s"""package $modelsPackage
       |
       |$imports
       |
       |enum $modelName {
       |${modelCases.map((switchCase _).tupled).mkString(System.lineSeparator())}
       |}
       |
       |object $modelName $extendsClause{$subtypeReadsWrites
       |  // Manual Reads and Writes implementations are provided for enum
       |  // until it is supported by Play Framework out of the box.
       |  // These implementations are based upon the code generated by
       |  // familyReads and familyWrites in play-json.
       |  given reads(using config: JsonConfiguration): Reads[$modelName] = Reads {
       |    case obj: JsObject => obj.value.get(config.discriminator) match {
       |      case Some(jsDiscriminator) => jsDiscriminator.validate[String].flatMap {
       |${modelCases
        .map(switchCaseRead(modelsPackage, modelName, _))
        .mkString(System.lineSeparator())}
       |        case _ =>
       |          JsError("error.invalid")
       |      }
       |      case _ => JsError(JsPath \\ config.discriminator, "error.missing.path")
       |    }
       |    case _ => JsError("error.expected.jsobject")
       |  }
       |
       |  given writes(using config: JsonConfiguration): Writes[$modelName] = Writes {
       |${modelCases
        .map(switchCaseWrite(modelsPackage, modelName, _))
        .mkString(System.lineSeparator())}
       |  }
       |
       |  given Format[$modelName] = Format(reads, writes)
       |}
       |""".stripMargin
  }

  def forIfThen(
    modelsPackage: QualifiedName,
    modelName: String,
    fields: List[(String, FieldType)]
  ): String = {
    val playImports = Map(
      PlayJsonPrefix -> Set(
        "Json",
        "JsonConfiguration",
        "JsError",
        "JsObject",
        "JsPath",
        "JsSuccess",
        "JsValue",
        "Format",
        "Reads",
        "Writes"
      )
    )

    val importPrefixes = playImports ++ Imports.importedSymbols(fields)
    val imports        = Imports.importsFor(modelsPackage, importPrefixes)
    val extendsClause  = FormatTraits.extendsClause(importPrefixes)
    val model          = modelsPackage / modelName
    val yesName        = model / "Yes"
    val noName         = model / "No"

    s"""package $modelsPackage
       |
       |$imports
       |
       |enum $modelName {
       |  case Yes(
       |  ${fields.map((ModelFields.field _).tupled).mkString("," + System.lineSeparator() + "  ")}
       |  )
       |  case No
       |}
       |
       |object $modelName $extendsClause{
       |  given yesReads: Reads[Yes]   = Json.reads[Yes]
       |  given yesWrites: Writes[Yes] = Json.writes[Yes]
       |
       |  // Manual Reads and Writes implementations are provided for enum
       |  // until it is supported by Play Framework out of the box.
       |  // These implementations are based upon the code generated by
       |  // familyReads and familyWrites in play-json.
       |  given reads(using config: JsonConfiguration): Reads[$modelName] = Reads {
       |    case obj: JsObject => obj.value.get(config.discriminator) match {
       |      case Some(jsDiscriminator) => jsDiscriminator.validate[String].flatMap {
       |        case yes if yes == config.typeNaming("$yesName") =>
       |          yesReads.reads(obj.value.getOrElse("_value", obj))
       |        case no  if no  == config.typeNaming("$noName")  =>
       |          JsSuccess(No)
       |        case _ =>
       |          JsError("error.invalid")
       |      }
       |      case _ => JsError(JsPath \\ config.discriminator, "error.missing.path")
       |    }
       |    case _ => JsError("error.expected.jsobject")
       |  }
       |
       |  given writes(using config: JsonConfiguration): Writes[$modelName] = Writes {
       |    case yes: Yes =>
       |      val output = yesWrites.writes(yes) match {
       |        case obj: JsObject => obj
       |        case other: JsValue => Json.obj("_value" -> other)
       |      }
       |      output ++ Json.obj(config.discriminator -> config.typeNaming("$yesName"))
       |    case No =>
       |      Json.obj(config.discriminator -> config.typeNaming("$noName"))
       |  }
       |
       |  given Format[$modelName] = Format(reads, writes)
       |}
       |""".stripMargin
  }

  def forDoWhile(
    modelsPackage: QualifiedName,
    modelName: String,
    fields: List[(String, FieldType)]
  ): String = {
    val importPrefixes = Imports.importedSymbols(fields)
    val imports        = Imports.importsFor(modelsPackage, importPrefixes)
    val extendsClause  = FormatTraits.extendsClause(importPrefixes)

    s"""package $modelsPackage
       |
       |import play.api.libs.json.{Json, Reads}
       |$imports
       |
       |case class $modelName(
       |${fields.map((ModelFields.field _).tupled).mkString("," + System.lineSeparator())}
       |)
       |
       |object $modelName $extendsClause{
       |  given Reads[$modelName] = Json.reads[$modelName]
       |}
       |""".stripMargin
  }

}
