serviceName: simple-journey

rootPages {
  index {viewRoute = "/"}
  beforeYouBegin {}
  checkYourAnswers {withDefaultController = false}
}

models {
  TaxRegime: [SA, VAT]
  AuditEvent: [
    {auditType: String},
    {description: String},
    {expectedGoLiveDate: LocalDate}
  ]
}

journeys {
  submission {
    pages {
      cipAssessmentTicket {
        answerType = String
      }
      cipAssessmentPage {
        answerType = String
      }
      serviceName {
        answerType = String
      }
      serviceDescription {
        answerType = String
      }
      dataDomain {
        answerType = String
      }
      addAnotherDataDomain {
        answerType = Boolean
      }
      addATaxRegime {
        answerType = Boolean
      }
      taxRegime {
        answerType = TaxRegime
      }
      addAnotherTaxRegime {
        answerType = Boolean
      }
      auditProvider {
        answerType = String
      }
      auditSource {
        answerType = String
      }
      auditEvent {
        answerType = AuditEvent
      }
      addAnotherAuditEvent {
        answerType = Boolean
      }
      addAnotherAuditSource {
        answerType = Boolean
      }
    }

    # journeys take 4 forms
    # 
    # cipAssessmentTicket                                   a plain page from the `pages` above
    # {if: addATaxRegime, then: ...}                        an answerType = Boolean choice page followed by a subjourney - an optional subjourney
    # {do: ..., while: addAnotherTaxRegime}                 a subjourney followed by an answerType = Boolean choice page - a loop
    # {switch: whichTaxRegime, case { SA: ..., VAT: ... }}  an enum choice page followed by the split subjourneys that depend upon that choice
    #
    # navigation decisions are generated by using this structure to determine where to go next
    #
    # optional subjourneys skip the subjourney if the leading boolean choice page is answered negatively
    # looping subjourneys add to the answer list and skip back to the first part of the subjourney if the boolean choice page is answered positively

    # using the CIP assessment YAML as an example, with some made-up stuff added to illustrate the possibilities
    journey = [
      cipAssessmentTicket,
      cipAssessmentPage,
      serviceName,
      serviceDescription,
      {do: dataDomain, while: addAnotherDataDomain, as: dataDomains},
      {if: addATaxRegime, then: {do: taxRegime, while: addAnotherTaxRegime, as: taxRegimes}},
      auditProvider,
      {do: [auditSource, {do: auditEvent, while: addAnotherAuditEvent, as: auditEvents}], while: addAnotherAuditSource, as: auditSources},
      checkYourAnswers
    ]
  }
}