/*
 * Copyright 2026 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.sbt.journey.templates

import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers
import uk.gov.hmrc.sbt.journey.models.{ClassType, FieldType, ListType, QualifiedName}

class JourneyModelSpec extends AnyFlatSpec with Matchers {
  "JourneyModel.forSwitchCase" should "render an enum model for a switch-case journey part with no subjourneys" in {
    val basePackage   = QualifiedName("uk.gov.hmrc.sbtjourneytest")
    val modelsPackage = basePackage / "models"
    JourneyModel.forSwitchCase(
      modelsPackage,
      "WhichTaxRegime",
      Map("SA" -> List.empty, "VAT" -> List.empty)
    ) shouldBe
      """package uk.gov.hmrc.sbtjourneytest.models
        |
        |import play.api.libs.json.{Format,JsError,JsObject,JsPath,JsValue,Json,JsonConfiguration,Reads,Writes}
        |
        |enum WhichTaxRegime {
        |  case SA
        |  case VAT
        |}
        |
        |object WhichTaxRegime {
        |  // Manual Reads and Writes implementations are provided for enum
        |  // until it is supported by Play Framework out of the box.
        |  // These implementations are based upon the code generated by
        |  // familyReads and familyWrites in play-json.
        |  given reads(using config: JsonConfiguration): Reads[WhichTaxRegime] = Reads {
        |    case obj: JsObject => obj.value.get(config.discriminator) match {
        |      case Some(jsDiscriminator) => jsDiscriminator.validate[String].flatMap {
        |        case sa if sa == config.typeNaming("uk.gov.hmrc.sbtjourneytest.models.WhichTaxRegime.SA")
        |          JsSuccess(SA)
        |        case vat if vat == config.typeNaming("uk.gov.hmrc.sbtjourneytest.models.WhichTaxRegime.VAT")
        |          JsSuccess(VAT)
        |        case _ =>
        |          JsError("error.invalid")
        |      }
        |      case _ => JsError(JsPath \ config.discriminator, "error.missing.path")
        |    }
        |    case _ => JsError("error.expected.jsobject")
        |  }
        |
        |  given writes(using config: JsonConfiguration): Writes[WhichTaxRegime] = Writes {
        |    case sa: SA =>
        |      Json.obj(config.discriminator -> config.typeNaming("uk.gov.hmrc.sbtjourneytest.models.WhichTaxRegime.SA"))
        |    case vat: VAT =>
        |      Json.obj(config.discriminator -> config.typeNaming("uk.gov.hmrc.sbtjourneytest.models.WhichTaxRegime.VAT"))
        |  }
        |
        |  given Format[WhichTaxRegime] = Format(reads, writes)
        |}
        |""".stripMargin
  }

  it should "render an enum model for a switch-case journey part with subjourneys" in {
    val basePackage   = QualifiedName("uk.gov.hmrc.sbtjourneytest")
    val modelsPackage = basePackage / "models"
    JourneyModel.forSwitchCase(
      modelsPackage,
      "WhichTaxRegime",
      Map(
        "SA"  -> List("saInfo" -> FieldType.STRING),
        "VAT" -> List("vatInfo" -> FieldType.STRING)
      )
    ) shouldBe
      """package uk.gov.hmrc.sbtjourneytest.models
        |
        |import play.api.libs.json.{Format,JsError,JsObject,JsPath,JsValue,Json,JsonConfiguration,Reads,Writes}
        |
        |enum WhichTaxRegime {
        |  case SA(
        |    saInfo: String
        |  )
        |  case VAT(
        |    vatInfo: String
        |  )
        |}
        |
        |object WhichTaxRegime {
        |  given saReads: Reads[SA] = Json.reads[SA]
        |  given vatReads: Reads[VAT] = Json.reads[VAT]
        |  given saWrites: Writes[SA] = Json.writes[SA]
        |  given vatWrites: Writes[VAT] = Json.writes[VAT]
        |
        |  // Manual Reads and Writes implementations are provided for enum
        |  // until it is supported by Play Framework out of the box.
        |  // These implementations are based upon the code generated by
        |  // familyReads and familyWrites in play-json.
        |  given reads(using config: JsonConfiguration): Reads[WhichTaxRegime] = Reads {
        |    case obj: JsObject => obj.value.get(config.discriminator) match {
        |      case Some(jsDiscriminator) => jsDiscriminator.validate[String].flatMap {
        |        case sa if sa == config.typeNaming("uk.gov.hmrc.sbtjourneytest.models.WhichTaxRegime.SA") =>
        |          saReads.reads(obj.value.getOrElse("_value", obj))
        |        case vat if vat == config.typeNaming("uk.gov.hmrc.sbtjourneytest.models.WhichTaxRegime.VAT") =>
        |          vatReads.reads(obj.value.getOrElse("_value", obj))
        |        case _ =>
        |          JsError("error.invalid")
        |      }
        |      case _ => JsError(JsPath \ config.discriminator, "error.missing.path")
        |    }
        |    case _ => JsError("error.expected.jsobject")
        |  }
        |
        |  given writes(using config: JsonConfiguration): Writes[WhichTaxRegime] = Writes {
        |    case sa: SA =>
        |      val output = saWrites.writes(sa) match {
        |        case obj: JsObject => obj
        |        case other: JsValue => Json.obj("_value" -> other)
        |      }
        |      output ++ Json.obj(config.discriminator -> config.typeNaming("uk.gov.hmrc.sbtjourneytest.models.WhichTaxRegime.SA"))
        |    case vat: VAT =>
        |      val output = vatWrites.writes(vat) match {
        |        case obj: JsObject => obj
        |        case other: JsValue => Json.obj("_value" -> other)
        |      }
        |      output ++ Json.obj(config.discriminator -> config.typeNaming("uk.gov.hmrc.sbtjourneytest.models.WhichTaxRegime.VAT"))
        |  }
        |
        |  given Format[WhichTaxRegime] = Format(reads, writes)
        |}
        |""".stripMargin
  }

  "JourneyModel.forIfThen" should "render an enum model for an if-then journey part" in {
    val basePackage   = QualifiedName("uk.gov.hmrc.sbtjourneytest")
    val modelsPackage = basePackage / "models"
    JourneyModel.forIfThen(
      modelsPackage,
      "AddATaxRegime",
      List("taxRegimes" -> ListType(ClassType(modelsPackage / "TaxRegime")))
    ) shouldBe
      """package uk.gov.hmrc.sbtjourneytest.models
        |
        |import play.api.libs.json.{Format,JsError,JsObject,JsPath,JsSuccess,JsValue,Json,JsonConfiguration,Reads,Writes}
        |
        |enum AddATaxRegime {
        |  case Yes(
        |    taxRegimes: List[TaxRegime]
        |  )
        |  case No
        |}
        |
        |object AddATaxRegime {
        |  given yesReads: Reads[Yes]   = Json.reads[Yes]
        |  given yesWrites: Writes[Yes] = Json.writes[Yes]
        |
        |  // Manual Reads and Writes implementations are provided for enum
        |  // until it is supported by Play Framework out of the box.
        |  // These implementations are based upon the code generated by
        |  // familyReads and familyWrites in play-json.
        |  given reads(using config: JsonConfiguration): Reads[AddATaxRegime] = Reads {
        |    case obj: JsObject => obj.value.get(config.discriminator) match {
        |      case Some(jsDiscriminator) => jsDiscriminator.validate[String].flatMap {
        |        case yes if yes == config.typeNaming("uk.gov.hmrc.sbtjourneytest.models.AddATaxRegime.Yes") =>
        |          yesReads.reads(obj.value.getOrElse("_value", obj))
        |        case no  if no  == config.typeNaming("uk.gov.hmrc.sbtjourneytest.models.AddATaxRegime.No")  =>
        |          JsSuccess(No)
        |        case _ =>
        |          JsError("error.invalid")
        |      }
        |      case _ => JsError(JsPath \ config.discriminator, "error.missing.path")
        |    }
        |    case _ => JsError("error.expected.jsobject")
        |  }
        |
        |  given writes(using config: JsonConfiguration): Writes[AddATaxRegime] = Writes {
        |    case yes: Yes =>
        |      val output = yesWrites.writes(yes) match {
        |        case obj: JsObject => obj
        |        case other: JsValue => Json.obj("_value" -> other)
        |      }
        |      output ++ Json.obj(config.discriminator -> config.typeNaming("uk.gov.hmrc.sbtjourneytest.models.AddATaxRegime.Yes"))
        |    case No =>
        |      Json.obj(config.discriminator -> config.typeNaming("uk.gov.hmrc.sbtjourneytest.models.AddATaxRegime.No"))
        |  }
        |
        |  given Format[AddATaxRegime] = Format(reads, writes)
        |}
        |""".stripMargin
  }

  "JourneyModel.forDoWhile" should "render a case class model for a do-while journey part" in {
    val basePackage   = QualifiedName("uk.gov.hmrc.sbtjourneytest")
    val modelsPackage = basePackage / "models"
    JourneyModel
      .forDoWhile(
        modelsPackage,
        "AuditSources",
        List(
          "auditSource" -> FieldType.STRING,
          "auditEvents" -> ListType(ClassType(modelsPackage / "AuditEvent"))
        )
      ) shouldBe
      """package uk.gov.hmrc.sbtjourneytest.models
        |
        |import play.api.libs.json.{Json, Reads}
        |
        |
        |case class AuditSources(
        |  auditSource: String,
        |  auditEvents: List[AuditEvent]
        |)
        |
        |object AuditSources {
        |  given Reads[AuditSources] = Json.reads[AuditSources]
        |}
        |""".stripMargin
  }
}
