serviceName: file-upload-journey

rootPages {
  index {}
  beforeYouStart {}
  checkYourAnswers {withDefaultController = false}
}

journeys {
  submission {
    pages {
      provideGoodsName {
        answerType = String
      }
      provideGoodsDescription {
        answerType = String
      }
      addConfidentialInformation {
        answerType = Boolean
      }
      provideConfidentialInformation {
        answerType = String
      }
      addSupportingDocuments {
        answerType = Boolean
      }
      uploadSupportingDocument {
        answerType = FileUpload
      }
      isDocumentConfidential {
        answerType = Boolean
      }
      addAnotherSupportingDocument {
        answerType = Boolean
      }
    }
    journey = [
      provideGoodsName,
      provideGoodsDescription,
      {if: addConfidentialInformation, then: provideConfidentialInformation},
      {
        if: addSupportingDocuments,
        then: {
          do: [uploadSupportingDocument, isDocumentConfidential],
          while: addAnotherSupportingDocument,
          as: supportingDocuments
        }
      },
      checkYourAnswers
    ]
  }
}